version: 2.1

jobs:
  emoji:
    name: "🧹 Emoji"
    docker:
      - image: cimg/base:stable
    steps:
      - run: "We love emojis. 🧹 "
  foo:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "I am Foo"
  bar:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "I am Bar"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Tests...."
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Lint check..."
  github_status_checked:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Indicate GitHub PR passed required checks
          command: |
            echo "All required checks done!"
            echo "This indicates this commit on Github (likely a PR) is good to go"

workflows:
  ci:
    jobs:
      - emoji
      - foo
      - bar:
          requires:
            - foo
      - test
      - lint
      - github_status_checked:
          requires:
            - test
            - lint

