version: 2.1

jobs:
  foo:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "I am Foo"
  bar:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "I am Bar"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Tests...."
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Lint check..."

workflows:
  ci:
    jobs:
      - foo
      - bar:
          requires:
            - foo
      - test
      - lint
